<a href="https://colab.research.google.com/github/channel1umut-lang/Deep-Learning/blob/main/0002_PyTorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
# pytorch datatypes - tensors

In [ ]:
torch.tensor(10)

tensor(10)

In [ ]:
scalar = torch.tensor(10)

In [ ]:
type(scalar)

torch.Tensor

In [ ]:
scalar + 5

tensor(15)

In [ ]:
scalar - 10

tensor(0)

In [ ]:
scalar

tensor(10)

In [ ]:
scalar.dim() # sifir boyutlu matrix

0

In [ ]:
scalar.shape

torch.Size([])

In [ ]:

scalar.item()

10

In [ ]:
type(scalar.item())

int

In [ ]:
numpy_int = np.int32(10)

In [ ]:
numpy_int

np.int32(10)

In [ ]:
numpy_int + 10

np.int32(20)

In [ ]:
numpy_int * 20

np.int32(200)

In [ ]:
scalar_from_np = torch.tensor(numpy_int)

In [ ]:
scalar_from_np

tensor(10, dtype=torch.int32)

In [ ]:
# dtype seems int32

In [ ]:
scalar.dtype

torch.int64

In [ ]:
#default seems to be 64, let's see how we can create a tensor with 32 bit with a regular int rather than np

In [ ]:
new_scalar = torch.tensor(25, dtype=torch.int32)

In [ ]:
new_scalar

tensor(25, dtype=torch.int32)

In [ ]:
new_scalar + 10

tensor(35, dtype=torch.int32)

In [ ]:
tensor_float = torch.tensor(3.14)

In [ ]:
tensor_float

tensor(3.1400)

In [ ]:
tensor_float.dtype # default degeri 64 bit

torch.float32

In [ ]:
tensor_float_64 = torch.tensor(3.14, dtype=torch.float64) # saklama kapasitesini degistirmek icin kullaniriz yani default degere degistirebiliyoruz.

In [ ]:
tensor_float_64

tensor(3.1400, dtype=torch.float64)

In [ ]:
# vectors

In [ ]:
vector = torch.tensor([2, 3])

In [ ]:
vector

tensor([2, 3])

In [ ]:
vector.dim()#function

1

In [ ]:
vector.ndim # attribute, 1 boyutlu yani sadece 1 kolonu ve voklu satirlari olan matrix gibi dusunebilirsin.

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector = torch.tensor([1,2,3])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
# count # of [ in order to figure out number of dimensions # yani koseli parantez sayisi boyut sayisini veriyor. Icindeki sayi da icindeki eleman sayisini veriyor.
# count elements in order to figure out shape

In [ ]:
matrix = torch.tensor([[1,2],[3,4]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
tensor_example = torch.tensor([[[1,2,3],[3,4,5],[4,5,6]]])

In [ ]:
tensor_example

tensor([[[1, 2, 3],
         [3, 4, 5],
         [4, 5, 6]]])

In [ ]:
tensor_example.ndim

3

In [ ]:
tensor_example.shape

torch.Size([1, 3, 3])

In [ ]:
# this means 1 dimension of 3 by 3

In [ ]:
tensor_example_2 = torch.tensor([[[1,2,3],[3,4,5],[4,5,6]],[[1,2,3],[3,4,5],[4,5,6]]])

In [ ]:
tensor_example_2

tensor([[[1, 2, 3],
         [3, 4, 5],
         [4, 5, 6]],

        [[1, 2, 3],
         [3, 4, 5],
         [4, 5, 6]]])

In [ ]:
tensor_example.ndim

3

In [ ]:
tensor_example_2.shape #yani 1. boyuttan 3 eleman(yani sira). 2. boyuttan 3 eleman(yani kolon sayisi). 3. boyuttan 2 eleman(yani derinlik sayisi)

torch.Size([2, 3, 3])

In [ ]:
# deep dive into dtypes - https://docs.pytorch.org/docs/stable/tensors.html#data-types

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # default or custom? yani degiskenin default degerini atar yani int32 mi float 32 mi vs...
                               device=None, # cpu, gpu? bunlardan hangisini kullanacagini secebiliyorsun.
                               requires_grad=False) # If autograd should record operations on the returned tensor # yani true yaptigimizda ogrenecek false yaptigimizda ogrenmeyecek.

In [ ]:
float_32_tensor.shape

torch.Size([3])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor.device

device(type='cpu')

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16