<a href="https://colab.research.google.com/github/channel1umut-lang/Deep-Learning/blob/main/0004_PyTorchOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
# remember we can create random ints, arrays etc. in numpy

In [ ]:
random_array = np.random.randn(3,5)

In [ ]:
random_array

array([[-0.70400683,  0.76628325,  2.06191066,  2.07711098,  0.91286786],
       [-0.31923222,  0.8705693 , -0.1363433 ,  0.24854405, -0.12270032],
       [ 0.24117927, -0.44164548, -0.25507253, -0.34904155,  0.4899313 ]])

In [ ]:
type(random_array)

numpy.ndarray

In [ ]:
random_array.shape

(3, 5)

In [ ]:
random_array.ndim

2

In [ ]:
# let's do this in pytorch

In [ ]:
random_matrix = torch.rand(size=(3, 5))

In [ ]:
random_matrix

tensor([[0.5251, 0.8655, 0.3968, 0.7900, 0.0520],
        [0.6716, 0.7496, 0.0569, 0.9546, 0.0853],
        [0.4367, 0.5744, 0.6751, 0.9169, 0.3747]])

In [ ]:
random_matrix.ndim

2

In [ ]:
random_matrix.shape

torch.Size([3, 5])

In [ ]:
random_matrix.dtype

torch.float32

In [ ]:
# we generally use 32 * 32 or 224 * 224 images in vision dl problems

In [ ]:
random_image_matrix = torch.rand(size=(224, 224, 3))

In [ ]:
random_image_matrix

tensor([[[0.4686, 0.6686, 0.4423],
         [0.3602, 0.1412, 0.6042],
         [0.6789, 0.0956, 0.9766],
         ...,
         [0.8288, 0.7440, 0.7717],
         [0.0314, 0.3799, 0.0541],
         [0.9230, 0.7327, 0.8646]],

        [[0.2144, 0.4029, 0.9621],
         [0.1695, 0.7919, 0.5282],
         [0.3037, 0.0848, 0.9302],
         ...,
         [0.3939, 0.7853, 0.1663],
         [0.2379, 0.8663, 0.3282],
         [0.4708, 0.0969, 0.8181]],

        [[0.0611, 0.8015, 0.7259],
         [0.4704, 0.8258, 0.6454],
         [0.8846, 0.0659, 0.5121],
         ...,
         [0.7026, 0.8572, 0.2541],
         [0.7499, 0.0956, 0.8085],
         [0.1551, 0.1611, 0.7148]],

        ...,

        [[0.4880, 0.5921, 0.8976],
         [0.1906, 0.7712, 0.3808],
         [0.6055, 0.7960, 0.3446],
         ...,
         [0.6589, 0.3476, 0.5731],
         [0.8351, 0.4771, 0.7142],
         [0.1422, 0.1943, 0.1998]],

        [[0.2789, 0.6522, 0.8497],
         [0.6792, 0.5895, 0.3405],
         [0.

In [ ]:
random_image_matrix.ndim

3

In [ ]:
random_image_matrix.shape

torch.Size([224, 224, 3])

In [ ]:
# we can create zeros and ones if we need some for matrix multiplication or anything else

In [ ]:
zeros = torch.zeros(size=(3, 2))

In [ ]:
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))

In [ ]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# or we can create ranges

In [ ]:
vector_with_arange = torch.arange(start=0, end=10, step=1)

In [ ]:
vector_with_arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
vector_with_arange = torch.arange(start=0, end=10, step=2)

In [ ]:
vector_with_arange

tensor([0, 2, 4, 6, 8])

In [ ]:
# let's say i need a similar vector with ones

In [ ]:
similar_ones = torch.ones_like(input=vector_with_arange)

In [ ]:
similar_ones

tensor([1, 1, 1, 1, 1])

In [ ]:
# basic math operations

In [ ]:
tensor = torch.tensor([1, 2, 3])

In [ ]:
tensor + 15

tensor([16, 17, 18])

In [ ]:
tensor * 12

tensor([12, 24, 36])

In [ ]:
tensor * 3.14

tensor([3.1400, 6.2800, 9.4200])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor = tensor + 10

In [ ]:
tensor

tensor([11, 12, 13])

In [ ]:
# we also have native methods for that

In [ ]:
tensor.subtract(10)

tensor([1, 2, 3])

In [ ]:
tensor

tensor([11, 12, 13])

In [ ]:
tensor = tensor.subtract(10)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor.multiply(20)

tensor([20, 40, 60])

In [ ]:
tensor.add(20)

tensor([21, 22, 23])

In [ ]:
tensor.divide(2)

tensor([0.5000, 1.0000, 1.5000])

In [ ]:
# can we only operate with scalars?

In [ ]:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
tensor + tensor

tensor([2, 4, 6])

In [ ]:
tensor - tensor

tensor([0, 0, 0])

In [ ]:
tensor / tensor

tensor([1., 1., 1.])

In [ ]:
# beware, in this case shapes should make sense

In [ ]:
tensor2 = torch.tensor([4,5])

In [ ]:
tensor + tensor2 # this is a common error when you work with tensors.

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

In [ ]:
tensor * tensor2

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0