<a href="https://colab.research.google.com/github/channel1umut-lang/Deep-Learning/blob/main/0005_PyTorchAggregationManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
tensor = torch.arange(0, 50, 5)

In [ ]:
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
tensor.min()

tensor(0)

In [ ]:
tensor.max()

tensor(45)

In [ ]:
tensor.sum()

tensor(225)

In [ ]:
tensor.median()

tensor(20)

In [ ]:
#tensor.mean() -> gives error!!

In [ ]:
# as you can see sometimes we get data type errors. we should know how to change dtypes when necessary

In [ ]:
tensor.dtype

torch.int64

In [ ]:
tensor.type(torch.float)

tensor([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [ ]:
tensor = tensor.type(torch.float)

In [ ]:
tensor.mean()

tensor(22.5000)

In [ ]:
# positional max, min (arg max min)

In [ ]:
tensor

tensor([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [ ]:
tensor.max()

tensor(45.)

In [ ]:
tensor.argmax()

tensor(9)

In [ ]:
#9th index

In [ ]:
tensor[9]

tensor(45.)

In [ ]:
tensor[0]

tensor(0.)

In [ ]:
#tensor[0][0] -> will throw error

In [ ]:
# index works as long as dimension fits

In [ ]:
matrix = torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0]

tensor([1, 2, 3])

In [ ]:
matrix[0][0]

tensor(1)

In [ ]:
#matrix[0][0][0]

In [ ]:
# manipulating tensors: reshaping, stacking, squeezing, unsqueezing

In [ ]:
x = torch.arange(1,10,1)

In [ ]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.shape

torch.Size([9])

In [ ]:
x_reshaped = x.reshape(1,9) # ana tensordaki yani X teki verileri kullanarak bizim istedigiimiz sekle uydurmaya calisiyor.

In [ ]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
# numbers should make sense

In [ ]:
# x_reshaped = x.reshape(1,20) -> will throw an error

In [ ]:
x_reshaped = x.reshape(3,3)

In [ ]:
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x_reshaped = x.reshape(9,1)

In [ ]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
# view function also behaves like reshape

In [ ]:
x_view = x.view(9,1)

In [ ]:
x_view

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# there are similarities & differences btw reshape & view. let's see

In [ ]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
x_reshaped[0] = 20

In [ ]:
x_reshaped

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [ ]:
x

tensor([20,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
x_view[0] = 10

In [ ]:
x_view

tensor([[10],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [ ]:
x

tensor([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
# they both change the original tensor if there is a change in them

In [ ]:
# however view only works with contigious tensors

In [ ]:
#https://medium.com/analytics-vidhya/pytorch-contiguous-vs-non-contiguous-tensor-view-understanding-view-reshape-73e10cdfa0dd

In [ ]:
# so that's why this will happen

In [ ]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

In [ ]:
x.is_contiguous()

True

In [ ]:
y = x.t()  # transpose -> NOT contiguous

In [ ]:
y.is_contiguous()

False

In [ ]:
x.view(1,6) # there is no error because it is a contigous value.

tensor([[1, 2, 3, 4, 5, 6]])

In [ ]:
#y.view(1,6) -> gives error because it is not contigous anymore.

In [ ]:
y.reshape(1,6)

tensor([[1, 4, 2, 5, 3, 6]])

In [ ]:
# as you can see the order is not what it used to be since we transposed this tensor

In [ ]:
# Stacking

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.stack([x,x,x,x], dim=0) # 4 tane x' i aldi ust uste koydu
#4 → en dıştaki grup sayısı
#2 → her grubun içindeki alt grup sayısı
#3 → en içteki eleman sayısı

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [ ]:
torch.stack([x,x,x,x], dim=1) # dim=1 → yeni boyutun yeri, 4 → liste uzunluğu. Yani Yeni boyutu index 1’e koy demek. Yani torch.Size([2, ? ,3]) soru isareti yerine 4 gelir. Burda 2 = 0 inci index
#“2 tane şey var her birinin içinde 4 tane şey var her birinin içinde 3 eleman var”
#NOTE!!!!!!!!!
#2 → en dıştaki grup sayısı
#4 → her grubun içindeki alt grup sayısı
#3 → en içteki eleman sayısı

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]])

In [ ]:
torch.stack([x,x,x,x], dim=2) # torch.Size([2, 3, ?]). Burda soru isaretinin yeri yeni boyutumun indexinin yerini gosteriyor gosteriyor.
#2 → en dıştaki grup sayısı
#3 → her grubun içindeki alt grup sayısı
#4 → en içteki eleman sayısı

tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]],

        [[4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6]]])

In [ ]:
# squeeze & unsqueeze -> removing all single dimensions from a tensor

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
y = x.unsqueeze(dim=0) # yeni bir boyut ekledi index 0'a bir saga kaydirdi. yeni shape bu oldu [?,2,3] soru isareti yerine yani 0. indexin yerine bir boyut daha ekledi.

In [ ]:
y

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [ ]:
y.shape

torch.Size([1, 2, 3])

In [ ]:
y = x.unsqueeze(dim=1) #yani index 1

In [ ]:
y

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [ ]:
y.shape
#2 → en dıştaki grup sayısı
#1 → her grubun içindeki alt grup sayısı
#4 → en içteki eleman sayısı

torch.Size([2, 1, 3])

In [ ]:
y = x.unsqueeze(dim=2)

In [ ]:
y

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

In [ ]:
y.shape

torch.Size([2, 3, 1])

In [ ]:
y = x.unsqueeze(dim=0)

In [ ]:
y

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [ ]:
z = y.unsqueeze(dim=0)

In [ ]:
z

tensor([[[[1, 2, 3],
          [4, 5, 6]]]])

In [ ]:
z.shape

torch.Size([1, 1, 2, 3])

In [ ]:
z.ndim

4

In [ ]:
t = z.squeeze() # gereksiz boyutlarin hepsini atti.

In [ ]:
t

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
t.shape

torch.Size([2, 3])

In [ ]:
t.ndim

2

In [ ]:
y

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [ ]:
y.ndim

3

In [ ]:
y = y.squeeze()

In [ ]:
y.shape

torch.Size([2, 3])

In [ ]:
y.ndim

2

In [ ]:
# permute -> rearrange the order of axes values

In [ ]:
x = torch.rand(size=(224, 224, 3))

In [ ]:
x.shape

torch.Size([224, 224, 3])

In [ ]:
x_permuted = x.permute(2, 0, 1) # axis 0->1, 1->2, 2->0

In [ ]:
x_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
# indexing & slicing

In [ ]:
a = torch.arange(1,10,1)

In [ ]:
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = a.reshape(1,3,3)

In [ ]:
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
a[0][0]

tensor([1, 2, 3])

In [ ]:
a[0][0][0]

tensor(1)

In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
a[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
a[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
a[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
a[0, 0, :] # same as a[0][0]

tensor([1, 2, 3])

In [ ]:
a[:,:,:] # gets all

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
a[0, 0, 0]

tensor(1)

In [ ]:
# random seeds

In [ ]:
RANDOM_SEED=10
#torch.manual_seed(seed=RANDOM_SEED)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9065, 0.4343, 0.2691, 0.9385],
        [0.2888, 0.6942, 0.2572, 0.0717],
        [0.4788, 0.2836, 0.2718, 0.3735]])