<a href="https://colab.research.google.com/github/channel1umut-lang/Deep-Learning/blob/main/0006_PyTorchDeviceSettings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
#NOT: if you are working with colab you can click runtime then change the runtime type

In [ ]:
torch.cuda.is_available() # check if gpu is available in your machine

False

In [ ]:
torch.backends.mps.is_available() # check if gpu is available in your machine (Mac silicons)

False

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu" # other than mac

In [ ]:
device

'cpu'

In [ ]:
device = "mps" if torch.backends.mps.is_available() else "cpu" # mac

In [ ]:
device

'cpu'

In [ ]:
# or just use this code for all

In [ ]:
import torch

if torch.cuda.is_available():
    device = "cuda"          # NVIDIA GPU
elif torch.xpu.is_available():
    device = "xpu"           # Intel GPU (Arc, Iris Xe, vs.)
elif torch.backends.mps.is_available():
    device = "mps"           # Apple Silicon GPU
else:
    device = "cpu"           # Central Processing Unit

print(f"Kullanılan cihaz: {device}")

Kullanılan cihaz: cpu


In [ ]:
device

'cpu'

In [ ]:
# what about the rest of the code?

In [ ]:
tensor = torch.tensor([1, 2, 3])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor.device

device(type='cpu')

In [ ]:
# i have a gpu available but the tensors that i created defaults to cpu
# what can i do?

In [ ]:
# 1) Manually handle everything

In [ ]:
tensor_on_gpu = tensor.to(device)

In [ ]:
tensor_on_gpu.device

device(type='cpu')

In [ ]:
# this is great but it can create some hassle for you when you want to move back and forth
# why would you want to move back to cpu btw?

In [ ]:
tensor_on_gpu.numpy()

array([1, 2, 3])

In [ ]:
# this will give you an error if you are on gpu since numpy does not leverage gpu

In [ ]:
tensor_numpy = tensor_on_gpu.cpu().numpy()

In [ ]:
tensor_numpy

array([1, 2, 3])

In [ ]:
#2) second option would be to use the context manager that came after 2.x versions

In [ ]:
device

'cpu'

In [ ]:
with torch.device(device):
    # All tensors created in this block will be on device
    tensor2 = torch.tensor([1,2,3])
    layer = torch.nn.Linear(20, 30) # we haven't covered layers yet but this will be created on gpu as well

In [ ]:
tensor2.device

device(type='cpu')

In [ ]:
layer.weight.device

device(type='cpu')

In [ ]:
#3) third option would be to use global definition of device for pytorch that came after 2.x versions

In [ ]:
device

'cpu'

In [ ]:
torch.set_default_device(device)

In [ ]:
tensor3 = torch.tensor([1,2,3])
layer2 = torch.nn.Linear(20, 30)


In [ ]:
tensor3.device

device(type='cpu')

In [ ]:
layer2.weight.device

device(type='cpu')

In [ ]:
torch.set_default_device("cpu")

In [ ]:
tensor3.device

device(type='cpu')

In [ ]:
tensor3 = torch.tensor([1,2,3])

In [ ]:
tensor3.device

device(type='cpu')

In [ ]:
# we can change the device back and forth globally like this but we need be careful again as we see in this example